### ISSUE TITLE
Random board number

### ISSUE THREAD

**Issue by Yeehaareal** [Dumuzy/KeizerForClubs#66]
To make more universal the software not only for chess, but also for other games, would be fantastic to random board numbers. We are using it for internal Novus tournament, where board (table) numbers are quite important.

**Comment by Dumuzy** [comment]
@Yeehaareal: I do not understand this completely. Please elaborate.

**Comment by Yeehaareal** [comment]
We play the Latvian game Novus, which is something like Carrom in India. The specification is that each table is a little bit different because made of wood.
For one day tournaments we use Round Robin or Swiss system with random tables. The difference is that if the player plays the second time on that table, he knows the specific, so that it is important that the next game he plays on another table. 
if we have 6 pairs of players, we use 3 tables. At the moment the better ones use 1st, then 2nd and the last ones use 3rd. Would be perfect that the table numbers would be in random, like 3, 2, 1 or 1, 3, 2 etc. In the software they can be in order, because we call the players to the table like - 1st table player A vs player B, 2nd table - player C vs player D etc.

**Comment by Dumuzy** [comment]
I see. But you say two different things:  
a. ...so that it is important that the next game he plays on another table.
b. Would be perfect that the table numbers would be in random.
These two are contradicting a bit. If purely random, it would still be possible that a player plays the second time on the same table.  So is purely random good enough? 
The other thing would be way more complicated.

**Comment by Yeehaareal** [comment]
Yes, purely random is good enough

**Comment by Yeehaareal** [comment]
In latest version, when using random board function, no excused players shown in pairing table

**Comment by Dumuzy** [comment]
Bug is fixed in 1.1.7.7.  I have implemented and fixed quite fast your special Novus wishes. 
Some donation would be appropriate and welcome.
