### ISSUE TITLE
Program won't run on several of A.D.'s computers  

### ISSUE THREAD

**Issue by Dumuzy** [Dumuzy/KeizerForClubs#82]
From A.D.: Mit Schrecken habe ich gerade festgestellt, dass sich das Programm auf meinem neu aufgesetzten Rechner (Windows 11) nicht starten lässt. Die Installation klappt, die nötige Windows Desktop Runtime habe ich installiert. Aber nach Klick auf die Anwendung startet diese einfach nicht, ohne Fehlermeldung. Dasselbe passiert auf meinem Notebook (Windows 10). Könnte das an der Firewall oder irgendwelchen anderen Sicherheitseinstellungen liegen? Auf meinem früheren Rechner lief alles problemlos. Ich habe auch versucht, die früheren Versionen 1.8.0.0. und 1.7.9.9 zu starten, mit demselben Ergebnis.

**Comment by Dumuzy** [comment]
Hab A.D. am 12.10.24 und 10.11.24 um weitere Hilfe per Email gebeten.

**Comment by prof-a-schmidt** [comment]
Kann das Problem bestätigen. Für 1.9.02 und auch für 2.0.0.2. Auf meinem Notebook (Win 10, 64 bit)  läuft alles bestens, auf dem PC (auch Win 10, 64 bit) startet das Programm nicht. Hier die Spezifikation des PC-Betriebssystems: 
Edition	Windows 10 Pro
Version	22H2
Installiert am	‎28.‎03.‎2023
Betriebssystembuild	19045.5131
Leistung	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by Dumuzy** [comment]
Hallo Schachfreund prof-a-schmidt,

da ich von A.D. nichtsmehr höre, vielleicht können Sie mir weiterhelfen, das zu debuggen. 
Bitte tun sie folgendes, wenn Sie mich bei der Fehlersuche unterstützen wollen.

1. Öffnen sie ein cmd-Fenster, in dem Verzeichnis, in dem das KeizerForClubs.exe  1.9.0.2 oder höher liegt.

2. Starten Sie das Programm per

KeizerForClubs.exe -d

aus dem cmd-Fenster. Der Parameter  -d hinten ist wichtig. 

3. Dann sollte eine Datei KFC2-00.log in dem selben Verzeichnis erzeugt werden. Lassen Sie mir diese zu kommen.

4. Wird eine solche Datei nicht im selben Verzeichnis erzeugt, so wurde sie evtl im Windows-Temp Verzeichnis erzeugt.  
Wo ist das Windows-Temp-Verzeichnis? Geben Sie im cmd-Fenster ein

echo %TEMP%

dann wird das angezeigt.

5. Wurde die Datei gar nicht erzeugt, so wird wohl tatsächlich das KFC vom Virenscanner dran gehindert, irgendwas zu tun.  Dann gibt es vllt ein Logfile oder einen Bericht oder sowas vom Virenscanner!? Da müßten Sie im Virenscanner suchen.

6. Oder sie könnten ausprobieren, den Virenscanner anders einzustellen oder mal abzustellen und gucken, ob es dann läuft. Dann hätte man wenigstens Gewißheit.

7. Wo haben Sie das Programm hinkopiert um es zu starten? Falls im oder unterhalb vom C:\Windows-Verzeichnis, wäre es einen Versuch wert, es woanders hinzukopieren und von dort aus zu starten.

**Comment by prof-a-schmidt** [comment]
Gerne. Ich habe zwei logs angehängt. Einmal das vom Notebook, wo das Programm läuft und eins vom PC, wo es das nicht tut.
[KFC2-00 (Notebook).log](https://github.com/user-attachments/files/17745317/KFC2-00.Notebook.log)
[KFC2-00 (PC).log](https://github.com/user-attachments/files/17745318/KFC2-00.PC.log)

**Comment by Dumuzy** [comment]
Sehr vielen Dank!  Das hilft mir sehr.  Bitte probieren Sie die neue Version 2.0.0.3 aus und berichten.

**Comment by prof-a-schmidt** [comment]
Leider unverändert. Log-Datei im Anhang. 
[KFC2-00.log](https://github.com/user-attachments/files/17826859/KFC2-00.log)

**Comment by Dumuzy** [comment]
Hallo Schachfreund Schmidt, 
ich habe eine neue Version gemacht, die 2.0.0.4. Bitte probieren Sie die aus und berichten mir. Vielen Dank!!

**Comment by prof-a-schmidt** [comment]
Nun springt der WIndows-Defender an, lässt sich aber beschwichtigen. Version 2.0.0.5 läuft aber leider immer noch nicht auf dem PC. Log-Datei im Anhang. 
[KFC2-00 (2.0.0.5).log](https://github.com/user-attachments/files/17932513/KFC2-00.2.0.0.5.log)

**Comment by Dumuzy** [comment]
Zur Dokumenation anbei der Anfang eines Logfiles von meinem Rechner. Auf dem läuft es. 
[KFC2-00.log](https://github.com/user-attachments/files/17939126/KFC2-00.log)
Unterschied ist, auf dem Rechner von Schachfreund Schmidt, wo's nicht läuft, ist Win 10 Pro. Auf menem, wo's läuft ist Win 10 Home. Beide Male 64bit.

**Comment by prof-a-schmidt** [comment]
Das Notebook auf dem es läuft ist auch Win 10 pro, 64 bit, das Gerät ist aber älter als der PC, auf dem es nicht läuft. Unten das log. Mysteriös.
[KFC2-00 (notebook).log](https://github.com/user-attachments/files/17939705/KFC2-00.notebook.log)

**Comment by Dumuzy** [comment]
Es  ist sogar auf beiden Ihrer Rechner genau dieselbe Win 10 Version, nämlich die  Version 10.0.19045.5131 Win 10 Pro.  In der Tat,  sehr mysteriös.

**Comment by Dumuzy** [comment]
Hallo Schachfreund Schmidt, 
ich habe den Verdacht, daß es an einem Virenscanner o.ä. liegt. Haben Sie da unterschiedliche auf beiden Rechnern? Gibt es vielleicht ein Logfile oder so eines Virenscanners?   Oh - und ich habe eine neue Version 2.0.0.6 gemacht, noch'n Versuch, mit erweitertem Logging. Wenn Sie die ausprobieren könnten... Viiielen Dank.

**Comment by Dumuzy** [comment]
HIer noch n Logfile von meinem Bürorechner, auch da läuft es. Win 10 Pro Version 10.0.19045.5011
[KFC2-00.Wxxxx16C.log](https://github.com/user-attachments/files/17950186/KFC2-00.Wxxxx16C.log)

**Comment by prof-a-schmidt** [comment]
Als Virenscanner existiert nur der bordeigene WIndow Defender und der behauptet, nichts getan zu haben. Wenn man ihn ausschaltet, ändert sich auch nichts. Version 2.0.0.6 läuft leider wieder nicht, Log im Anhang. Habe auch mal versucht, das Programm von einem anderen Verzeichnis zu starten. Ohne Erfolg. 

Falls das relevant werden könnte: der Rechner auf dem es nicht läuft ist ein HP, Gerätespez:

Prozessor	12th Gen Intel(R) Core(TM) i9-12900   2.40 GHz
Installierter RAM	32,0 GB (31,7 GB verwendbar)

[KFC2-00.log](https://github.com/user-attachments/files/17957734/KFC2-00.log)

**Comment by Dumuzy** [comment]
Noch ne Version, 2.0.0.8 gemacht. Bitte starten Sie die mit den Parametern   -d -fx
Das könnte weitere Erkenntnis bringen. Vielen Dank.

**Comment by prof-a-schmidt** [comment]
Leider mit Version 2.0.0.8 immer noch unverändert. Log-Datei (mit -d -fx) im Anhang. 
[KFC2-00.log](https://github.com/user-attachments/files/17990655/KFC2-00.log)

**Comment by Dumuzy** [comment]
dumpbin /dependents System.Data.SQLite.dll   
gibt das aus:
Dump of file System.Data.SQLite.dll
File Type: DLL
  Image has the following dependencies:
    KERNEL32.dll
    MSVCR100.dll
    mscoree.dll
Das sind doch alles WIndows-Standard dlls!?

**Comment by Dumuzy** [comment]
Hallo prof-a-schmidt, 
ich habe die neue Version 2.0.0.9 gemacht, die sollte auch laufen, wenn die MSVCR100.dll auf einem Rechner fehlt.

**Comment by prof-a-schmidt** [comment]
Hurra! Version 2.0.0.9 läuft. Danke!

**Comment by Dumuzy** [comment]
Prof-a-schmidt, Ihnen nochmals vielen vielen Dank!

**Comment by Dumuzy** [comment]
Von A.D. hör ich nichts mehr, trotz mehrfacher Nachfrage. Da ich sehr stark annehme, daß sine Bug derselbe war wie der bei prof-a-schmidt, seh ich diesen Bug nun als gefixt an.

**Comment by Dumuzy** [comment]
Prof-a-schmidt, Sie haben mich außerordentlich gut unterstützt bei diesem Problem/Projekt. 

Vielleicht haben Sie ja Lust, mich auch bei einem anderen Projekt ein bischen zu unterstützen. Ich bitte Sie darum. 
Ich habe eine Android-App geschrieben, die zum Trainieren von Springergabeln beim Schach dient. 
Ich brauche noch ein paar Tester, um die App in den Playstore stellen zu können. Der Test ist mehr eine Formalität, da die App schon seit ca einem Jahr von einigen meiner Vereinskollegen verwendet wird. 
Details gibt es da: https://lichess.org/@/Alakaluf/blog/haben-sie-jemals-eine-springergabel-ubersehen/B1QqyC2p   
Viele Grüße!
