### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Dumuzy** [Dumuzy/KeizerForClubs#84]
From RGmember of Lichess: 

I'm using Keizerforclubs for my club, it's awesome. Thanks a lot for this masterpiece !
I got some ideas for new features :
1. The possibility of adding player's category (young / senior / veteran) for each player.
2. The possibility to have one standing per category
3. The possibility to have one podium per category (only the first 3 players per category)

The idea is to make the standing more positive for the young players of my club, with more possibility to be in good place in a standing. Also, the idea behind the podium is to hide the lowest players in order to not demoralize them :)

Have a good day :)

**Comment by pascalprog** [comment]
I am glad to see that Lichess is helping to raise awareness of this excellent software and a more interesting pairing method for chess clubs. 😃
